### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by fessehaye** [albertasmash/albertasmash.github.io#1]
-Add link to smash.gg page and facebook event(done)
-Add biography for JT4.(done)
-Add paypal link to either ssbuniversity@gmail.com or info@4jarrett.me(almost done)
-Add images of previous year or of Jarrett(done)
-Change map to facebook event location(done)
-Add proper contact information with info@4jarrett.me
-Update profolio images(done)
-Change that event counter to either represent 
----amount raised in previous years(600,?,2400)
----people currently preregistered(api call to fb event?)
-replace current contact form with event info and but contact info on the div below(done)
Feel free to add anymore tasks/ideas

**Comment by tblock007** [comment]
-embed twitch player?

**Comment by fessehaye** [comment]
Ooh I like that idea

**Comment by tblock007** [comment]
-History section has a (see end of article) that should probably be removed?
-Let's remember to make the width of each section consistent once everything is done
